image: Ubuntu2004

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

install:
- sudo apt update -qq
- sudo apt install -qq -y git build-essential libcapstone-dev libssl-dev cmake make parallel doxygen git-lfs rpm liblief-dev python3-dev python3 python3-pip
- git submodule update --init --recursive

test_script:
- make threads=4 args="-DBUILD_PYTHON_BINDINGS=true"
- python3 -m pip wheel -v -e .
- mv *.whl build/
- make pkg
- make dist

artifacts:
  - path: build/*.deb
  - path: build/*.rpm
  - path: build/*.tar.gz
  - path: build/*.zip

build: off