image:
  - Visual Studio 2019
  - Ubuntu2004

platform:
  - x64

configuration:
- Release

for:
  -
    matrix:
      only:
        - image: Ubuntu2004
    platform: Any CPU
    environment:
      APPVEYOR_YML_DISABLE_PS_LINUX: true
    install:
      - sudo apt update -qq
      - sudo apt install -qq -y git build-essential libcapstone-dev libssl-dev cmake make parallel doxygen git-lfs rpm liblief-dev python3-dev python3 python3-pip
      - git submodule update --init --recursive
    test_script:
      - make threads=4 args="-DBUILD_PYTHON_BINDINGS=true"
      - python3 -m pip wheel -e .
      - mv *.whl build/
      - make pkg
      - make dist
    artifacts:
      - path: build/*.deb
      - path: build/*.rpm
      - path: build/*.tar.gz
      - path: build/*.zip
      - path: build/*.whl
      - path: build/pybinlex*.so
  -
    matrix:
      only:
        - image: Visual Studio 2017
    configuration:
      - Release
    platform: Any CPU
    install:
      - git submodule update --init --recursive
      - set PATH=C:\Program Files\CMake\bin;%PATH%
    test_script:
      - ps: mkdir build
      - ps: cd build/
      - ps: cmake ..
      - ps: cmake --build .

build: off